### ISSUE TITLE
[BUG] Rotating canvas in Lock View removes grid

### ISSUE THREAD

**Issue by matt-derrick** [MaterialFoundry/LockView#125] opened 2024-10-06 18:39 UTC
**Setup**
 - OS: Windows 11
 - Browser: All (tested Firefox and Chrome)
 - Module version: 1.5.10
 - Foundry version: 12.331
 - Gaming system & version: SWAE 4.1.1
 - Any other modules enabled: yes

**Describe the bug**
Changing the 'rotation' setting on the lock view settings tab of any scene removes the grid set for that scene for the lock view player (the grid still displays for the GM). Changing the rotation back to Landscape makes the grid appear again for that user.

**Screenshots**
n/a

**Console Log**
none

**Additional context**
I wouldn't be surprised if using a grid on a rotated map just wasn't supported at ALL, since the whole canvas is being rotated, but it does cause some confusion, so perhaps adding 'this will remove any grid in use' to the Rotation option description text might be helpful for some users.

**Comment by MaterialFoundry** [comment] 2024-10-06 18:57
Duplicate of #119

**Closed by MaterialFoundry** 2024-10-06 18:57 UTC
Labels: bug
